In [1]:
import pandas as pd

path = "../data/raw/10.35097-1969/10.35097-1969/data/dataset/cell_eisv2/cell_eisv2_P001_1_S01_C10.csv"
df = pd.read_csv(path, sep=";")

# One row per unique combination of timestamp + soc_nom + is_rt should be one spectrum (28 freq points)
spectra = df.groupby(["timestamp_s", "soc_nom", "is_rt"]).size()
print("Number of distinct spectra in this file:", len(spectra))
print(spectra.describe())   # should cluster near 28 if grouping is right

# Does timestamp_s increase monotonically? (i.e. can it order check-ups in time)
print("\nUnique timestamps, in order:")
print(sorted(df["timestamp_s"].unique())[:10])

# Does cyc_charged change per check-up, or is it constant?
print("\ncyc_charged unique values:", df["cyc_charged"].unique())

Number of distinct spectra in this file: 291
count    291.0
mean      29.0
std        0.0
min       29.0
25%       29.0
50%       29.0
75%       29.0
max       29.0
dtype: float64

Unique timestamps, in order:
[np.float64(1665653927.0), np.float64(1665659081.0), np.float64(1665669260.0), np.float64(1665679641.0), np.float64(1665689716.0), np.float64(1665700156.0), np.float64(1665736717.0), np.float64(1665747274.0), np.float64(1665757709.0), np.float64(1665770490.0)]

cyc_charged unique values: [1 0]

In [2]:
import pandas as pd

# unique spectrum timestamps, sorted
timestamps = sorted(df["timestamp_s"].unique())

# convert to human-readable dates
dates = pd.to_datetime(timestamps, unit="s")
print("First 10 dates:")
print(dates[:10])

# gap between each spectrum and the next, in hours
gaps_hours = pd.Series(timestamps).diff() / 3600
print("\nGap between consecutive spectra (hours):")
print(gaps_hours.describe())

# how many gaps are "big" (more than 5 days = likely a new check-up)?
big_gaps = gaps_hours[gaps_hours > 24*5]
print("\nNumber of gaps > 5 days:", len(big_gaps))
print(big_gaps.head(10))

First 10 dates:
DatetimeIndex(['2022-10-13 09:38:47', '2022-10-13 11:04:41',
               '2022-10-13 13:54:20', '2022-10-13 16:47:21',
               '2022-10-13 19:35:16', '2022-10-13 22:29:16',
               '2022-10-14 08:38:37', '2022-10-14 11:34:34',
               '2022-10-14 14:28:29', '2022-10-14 18:01:30'],
              dtype='datetime64[s]', freq=None)

Gap between consecutive spectra (hours):
count    290.000000
mean      49.208415
std      148.121557
min        1.161667
25%        1.279167
50%        1.400417
75%        2.500833
max      982.888889
dtype: float64

Number of gaps > 5 days: 28
11     125.287222
21     471.025000
31     480.246667
46     460.407778
56     478.398333
66     481.690556
76     481.829444
86     483.258889
96     484.512500
106    480.661111
dtype: float64

In [6]:
def assign_cu_index(timestamps: pd.Series, gap_threshold_hours: float = 24.0) -> pd.Series:
    """
    Assigns a check-up (CU) index to each timestamp based on time gaps.

    timestamps: raw timestamp_s values (seconds since epoch), one per spectrum.
    gap_threshold_hours: any gap larger than this marks the start of a new CU.
    Returns: integer Series, same length/order as input, giving CU index (0,1,2,...).
    """
    ts = timestamps.reset_index(drop=True)
    order = ts.sort_values().index          # chronological order of the original positions
    sorted_ts = ts.loc[order]

    gap_seconds = sorted_ts.diff()
    is_new_cu = gap_seconds > (gap_threshold_hours * 3600)
    is_new_cu.iloc[0] = False               # first spectrum starts CU 0, not a "new" one

    cu_in_sorted_order = is_new_cu.cumsum()

    # map back onto the original (unsorted) order
    cu_index = pd.Series(index=order, data=cu_in_sorted_order.values).sort_index()
    return cu_index

In [4]:
cu_index = assign_cu_index(pd.Series(timestamps))
print(cu_index.value_counts().sort_index())

0     11
1     10
2     10
3     15
4     10
5     10
6     10
7     10
8     10
9     10
10    10
11     5
12     5
13    10
14    10
15    10
16    10
17    10
18    10
19    10
20    10
21    10
22    10
23    10
24    10
25    10
26    10
27    10
28    10
29     5
Name: count, dtype: int64

In [7]:
sorted_ts = pd.Series(timestamps).sort_values().reset_index(drop=True)
gap_hours = sorted_ts.diff() / 3600

# print index, gap-to-previous, and date, for anything near our suspicious CUs
inspect_df = pd.DataFrame({
    "timestamp": sorted_ts,
    "date": pd.to_datetime(sorted_ts, unit="s"),
    "gap_hours": gap_hours
})
print(inspect_df.iloc[20:45])   # around where CU 3 (15 spectra) would sit
print(inspect_df.iloc[125:150]) # around where CU 11/12 (5+5) would sit

       timestamp                date   gap_hours
20  1.666341e+09 2022-10-21 08:34:45    2.560000
21  1.668037e+09 2022-11-09 23:36:15  471.025000
22  1.668045e+09 2022-11-10 01:53:57    2.295000
23  1.668054e+09 2022-11-10 04:26:06    2.535833
24  1.668063e+09 2022-11-10 06:43:40    2.292778
25  1.668068e+09 2022-11-10 08:14:02    1.506111
26  1.668095e+09 2022-11-10 15:37:29    7.390833
27  1.668103e+09 2022-11-10 18:01:14    2.395833
28  1.668112e+09 2022-11-10 20:18:52    2.293889
29  1.668120e+09 2022-11-10 22:41:07    2.370833
30  1.668127e+09 2022-11-11 00:33:08    1.866944
31  1.669856e+09 2022-12-01 00:47:56  480.246667
32  1.669863e+09 2022-12-01 02:54:00    2.101111
33  1.669870e+09 2022-12-01 04:53:38    1.993889
34  1.669878e+09 2022-12-01 06:55:42    2.034444
35  1.669883e+09 2022-12-01 08:15:06    1.323333
36  1.669918e+09 2022-12-01 18:04:50    9.828889
37  1.669925e+09 2022-12-01 20:05:04    2.003889
38  1.669932e+09 2022-12-01 22:00:06    1.917222
39  1.669939e+09 2022-12-02 00:02:22    2.037778
40  1.669947e+09 2022-12-02 02:04:36    2.037222
41  1.669981e+09 2022-12-02 11:34:08    9.492222
42  1.669987e+09 2022-12-02 13:17:38    1.725000
43  1.669994e+09 2022-12-02 15:11:44    1.901667
44  1.670002e+09 2022-12-02 17:22:42    2.182778
        timestamp                date   gap_hours
125  1.684514e+09 2023-05-19 16:33:51    1.226389
126  1.686188e+09 2023-06-08 01:29:57  464.935000
127  1.686192e+09 2023-06-08 02:41:56    1.199722
128  1.686197e+09 2023-06-08 04:01:50    1.331667
129  1.686201e+09 2023-06-08 05:16:27    1.243611
130  1.686206e+09 2023-06-08 06:35:10    1.311944
131  1.686231e+09 2023-06-08 13:36:25    7.020833
132  1.686236e+09 2023-06-08 14:50:53    1.241111
133  1.686241e+09 2023-06-08 16:21:24    1.508611
134  1.686247e+09 2023-06-08 18:02:56    1.692222
135  1.686252e+09 2023-06-08 19:16:17    1.222500
136  1.687987e+09 2023-06-28 21:21:09  482.081111
137  1.687992e+09 2023-06-28 22:40:21    1.320000
138  1.687997e+09 2023-06-28 23:57:00    1.277500
139  1.688001e+09 2023-06-29 01:12:01    1.250278
140  1.688006e+09 2023-06-29 02:36:05    1.401111
141  1.688030e+09 2023-06-29 09:05:07    6.483889
142  1.688034e+09 2023-06-29 10:21:13    1.268333
143  1.688039e+09 2023-06-29 11:51:10    1.499167
144  1.688045e+09 2023-06-29 13:28:52    1.628333
145  1.688050e+09 2023-06-29 14:45:37    1.279167
146  1.689802e+09 2023-07-19 21:23:08  486.625278
147  1.689806e+09 2023-07-19 22:37:23    1.237500
148  1.689811e+09 2023-07-19 23:54:01    1.277222
149  1.689815e+09 2023-07-20 01:10:56    1.281944

In [8]:
# recompute in sorted (chronological) order for clarity
sorted_ts = pd.Series(timestamps).sort_values().reset_index(drop=True)
gap_hours = sorted_ts.diff() / 3600
is_new_cu = gap_hours > 24
is_new_cu.iloc[0] = False
cu_sorted = is_new_cu.cumsum()

inspect_df = pd.DataFrame({
    "timestamp": sorted_ts,
    "date": pd.to_datetime(sorted_ts, unit="s"),
    "gap_hours": gap_hours,
    "cu": cu_sorted
})

# find exact row range for each suspicious CU, with a little padding around it
for target_cu in [2, 3, 4, 10, 11, 12, 13, 28, 29]:
    idx = cu_sorted[cu_sorted == target_cu].index
    print(f"--- CU {target_cu}: rows {idx.min()}–{idx.max()}, count={len(idx)} ---")
    print(inspect_df.loc[max(idx.min()-1, 0) : idx.max()+1])
    print()

--- CU 2: rows 21–30, count=10 ---
       timestamp                date   gap_hours  cu
20  1.666341e+09 2022-10-21 08:34:45    2.560000   1
21  1.668037e+09 2022-11-09 23:36:15  471.025000   2
22  1.668045e+09 2022-11-10 01:53:57    2.295000   2
23  1.668054e+09 2022-11-10 04:26:06    2.535833   2
24  1.668063e+09 2022-11-10 06:43:40    2.292778   2
25  1.668068e+09 2022-11-10 08:14:02    1.506111   2
26  1.668095e+09 2022-11-10 15:37:29    7.390833   2
27  1.668103e+09 2022-11-10 18:01:14    2.395833   2
28  1.668112e+09 2022-11-10 20:18:52    2.293889   2
29  1.668120e+09 2022-11-10 22:41:07    2.370833   2
30  1.668127e+09 2022-11-11 00:33:08    1.866944   2
31  1.669856e+09 2022-12-01 00:47:56  480.246667   3

--- CU 3: rows 31–45, count=15 ---
       timestamp                date   gap_hours  cu
30  1.668127e+09 2022-11-11 00:33:08    1.866944   2
31  1.669856e+09 2022-12-01 00:47:56  480.246667   3
32  1.669863e+09 2022-12-01 02:54:00    2.101111   3
33  1.669870e+09 2022-12-01 04:53:38    1.993889   3
34  1.669878e+09 2022-12-01 06:55:42    2.034444   3
35  1.669883e+09 2022-12-01 08:15:06    1.323333   3
36  1.669918e+09 2022-12-01 18:04:50    9.828889   3
37  1.669925e+09 2022-12-01 20:05:04    2.003889   3
38  1.669932e+09 2022-12-01 22:00:06    1.917222   3
39  1.669939e+09 2022-12-02 00:02:22    2.037778   3
40  1.669947e+09 2022-12-02 02:04:36    2.037222   3
41  1.669981e+09 2022-12-02 11:34:08    9.492222   3
42  1.669987e+09 2022-12-02 13:17:38    1.725000   3
43  1.669994e+09 2022-12-02 15:11:44    1.901667   3
44  1.670002e+09 2022-12-02 17:22:42    2.182778   3
45  1.670006e+09 2022-12-02 18:40:29    1.296389   3
46  1.671664e+09 2022-12-21 23:04:57  460.407778   4

--- CU 4: rows 46–55, count=10 ---
       timestamp                date   gap_hours  cu
45  1.670006e+09 2022-12-02 18:40:29    1.296389   3
46  1.671664e+09 2022-12-21 23:04:57  460.407778   4
47  1.671670e+09 2022-12-22 00:51:03    1.768333   4
48  1.671678e+09 2022-12-22 02:57:09    2.101667   4
49  1.671685e+09 2022-12-22 04:52:59    1.930556   4
50  1.671690e+09 2022-12-22 06:12:04    1.318056   4
51  1.671727e+09 2022-12-22 16:32:35   10.341944   4
52  1.671733e+09 2022-12-22 18:19:13    1.777222   4
53  1.671740e+09 2022-12-22 20:14:07    1.915000   4
54  1.671747e+09 2022-12-22 22:08:33    1.907222   4
55  1.671754e+09 2022-12-23 00:07:13    1.977778   4
56  1.673476e+09 2023-01-11 22:31:07  478.398333   5

--- CU 10: rows 106–115, count=10 ---
        timestamp                date   gap_hours  cu
105  1.680816e+09 2023-04-06 21:18:21    1.341944   9
106  1.682546e+09 2023-04-26 21:58:01  480.661111  10
107  1.682551e+09 2023-04-26 23:11:22    1.222500  10
108  1.682556e+09 2023-04-27 00:34:08    1.379444  10
109  1.682560e+09 2023-04-27 01:51:33    1.290278  10
110  1.682565e+09 2023-04-27 03:09:27    1.298333  10
111  1.682622e+09 2023-04-27 19:04:01   15.909444  10
112  1.682627e+09 2023-04-27 20:18:32    1.241944  10
113  1.682632e+09 2023-04-27 21:47:17    1.479167  10
114  1.682638e+09 2023-04-27 23:24:55    1.627222  10
115  1.682642e+09 2023-04-28 00:38:12    1.221389  10
116  1.684361e+09 2023-05-17 22:00:50  477.377222  11

--- CU 11: rows 116–120, count=5 ---
        timestamp                date   gap_hours  cu
115  1.682642e+09 2023-04-28 00:38:12    1.221389  10
116  1.684361e+09 2023-05-17 22:00:50  477.377222  11
117  1.684365e+09 2023-05-17 23:15:03    1.236944  11
118  1.684370e+09 2023-05-18 00:32:05    1.283889  11
119  1.684374e+09 2023-05-18 01:48:08    1.267500  11
120  1.684379e+09 2023-05-18 03:08:01    1.331389  11
121  1.684494e+09 2023-05-19 10:52:54   31.748056  12

--- CU 12: rows 121–125, count=5 ---
        timestamp                date   gap_hours  cu
120  1.684379e+09 2023-05-18 03:08:01    1.331389  11
121  1.684494e+09 2023-05-19 10:52:54   31.748056  12
122  1.684498e+09 2023-05-19 12:13:39    1.345833  12
123  1.684504e+09 2023-05-19 13:42:51    1.486667  12
124  1.684510e+09 2023-05-19 15:20:16    1.623611  12
125  1.684514e+09 2023-05-19 16:33:51    1.226389  12
126  1.686188e+09 2023-06-08 01:29:57  464.935000  13

--- CU 13: rows 126–135, count=10 ---
        timestamp                date   gap_hours  cu
125  1.684514e+09 2023-05-19 16:33:51    1.226389  12
126  1.686188e+09 2023-06-08 01:29:57  464.935000  13
127  1.686192e+09 2023-06-08 02:41:56    1.199722  13
128  1.686197e+09 2023-06-08 04:01:50    1.331667  13
129  1.686201e+09 2023-06-08 05:16:27    1.243611  13
130  1.686206e+09 2023-06-08 06:35:10    1.311944  13
131  1.686231e+09 2023-06-08 13:36:25    7.020833  13
132  1.686236e+09 2023-06-08 14:50:53    1.241111  13
133  1.686241e+09 2023-06-08 16:21:24    1.508611  13
134  1.686247e+09 2023-06-08 18:02:56    1.692222  13
135  1.686252e+09 2023-06-08 19:16:17    1.222500  13
136  1.687987e+09 2023-06-28 21:21:09  482.081111  14

--- CU 28: rows 276–285, count=10 ---
        timestamp                date   gap_hours  cu
275  1.711660e+09 2024-03-28 21:08:26    1.191389  27
276  1.713413e+09 2024-04-18 03:59:06  486.844444  28
277  1.713417e+09 2024-04-18 05:10:06    1.183333  28
278  1.713422e+09 2024-04-18 06:27:17    1.286389  28
279  1.713426e+09 2024-04-18 07:43:18    1.266944  28
280  1.713431e+09 2024-04-18 09:04:08    1.347222  28
281  1.713451e+09 2024-04-18 14:42:15    5.635278  28
282  1.713456e+09 2024-04-18 15:56:43    1.241111  28
283  1.713461e+09 2024-04-18 17:20:40    1.399167  28
284  1.713467e+09 2024-04-18 18:58:28    1.630000  28
285  1.713471e+09 2024-04-18 20:09:47    1.188611  28
286  1.717009e+09 2024-05-29 19:03:07  982.888889  29

--- CU 29: rows 286–290, count=5 ---
        timestamp                date   gap_hours  cu
285  1.713471e+09 2024-04-18 20:09:47    1.188611  28
286  1.717009e+09 2024-05-29 19:03:07  982.888889  29
287  1.717014e+09 2024-05-29 20:13:44    1.176944  29
288  1.717018e+09 2024-05-29 21:29:40    1.265556  29
289  1.717023e+09 2024-05-29 22:46:27    1.279722  29
290  1.717028e+09 2024-05-30 00:05:12    1.312500  29

In [12]:
# build a lookup: timestamp -> CU index
ts_to_cu = pd.Series(cu_sorted.values, index=sorted_ts.values)

# map onto every row of the full raw dataframe (via timestamp_s)
df["cu"] = df["timestamp_s"].map(ts_to_cu)

# now this works — same length as df
cu3_rows = df[df["cu"] == 3]
print(cu3_rows[["soc_nom", "is_rt", "cyc_charged"]].drop_duplicates())

      soc_nom  is_rt  cyc_charged
899        10      1            1
928        30      1            1
957        50      1            1
986        70      1            1
1015       90      1            1
1044       90      0            0
1073       70      0            0
1102       50      0            0
1131       30      0            0
1160       10      0            0

In [2]:
import pandas as pd

path = "../data/raw/10.35097-1969/10.35097-1969/data/dataset/cell_eisv2/cell_eisv2_P001_1_S01_C10.csv"
df = pd.read_csv(path, sep=";")

timestamps = sorted(df["timestamp_s"].unique())

sorted_ts = pd.Series(timestamps).sort_values().reset_index(drop=True)
gap_hours = sorted_ts.diff() / 3600
is_new_cu = gap_hours > 24
is_new_cu.iloc[0] = False
cu_sorted = is_new_cu.cumsum()

# map CU index back onto every row of df
ts_to_cu = pd.Series(cu_sorted.values, index=sorted_ts.values)
df["cu"] = df["timestamp_s"].map(ts_to_cu)

In [3]:
cu3 = df[df["cu"] == 3]

combo_counts = cu3.groupby(["soc_nom", "is_rt", "cyc_charged"])["timestamp_s"].nunique()
print(combo_counts)

duplicated_combos = combo_counts[combo_counts > 1].index
for soc, rt, chg in duplicated_combos:
    subset = cu3[(cu3["soc_nom"] == soc) & (cu3["is_rt"] == rt) & (cu3["cyc_charged"] == chg)]
    print(f"\nsoc={soc}, is_rt={rt}, cyc_charged={chg}:")
    print(subset.groupby("timestamp_s")["valid"].agg(["min", "max", "count"]))

soc_nom  is_rt  cyc_charged
10       0      0              2
         1      1              1
30       0      0              2
         1      1              1
50       0      0              2
         1      1              1
70       0      0              2
         1      1              1
90       0      0              2
         1      1              1
Name: timestamp_s, dtype: int64

soc=10, is_rt=0, cyc_charged=0:
              min  max  count
timestamp_s
1.669947e+09    1    1     29
1.670006e+09    1    1     29

soc=30, is_rt=0, cyc_charged=0:
              min  max  count
timestamp_s
1.669939e+09    1    1     29
1.670002e+09    1    1     29

soc=50, is_rt=0, cyc_charged=0:
              min  max  count
timestamp_s
1.669932e+09    1    1     29
1.669994e+09    1    1     29

soc=70, is_rt=0, cyc_charged=0:
              min  max  count
timestamp_s
1.669925e+09    1    1     29
1.669987e+09    1    1     29

soc=90, is_rt=0, cyc_charged=0:
              min  max  count
timestamp_s
1.669918e+09    1    1     29
1.669981e+09    1    1     29

In [7]:
def assign_cu_index(timestamps: pd.Series, gap_threshold_hours: float = 24.0) -> pd.Series:
    """
    Assigns a check-up (CU) index to each timestamp based on time gaps.

    timestamps: raw timestamp_s values (seconds since epoch), one per spectrum.
    gap_threshold_hours: any gap larger than this marks the start of a new CU.
    Returns: integer Series, same length/order as input, giving CU index (0,1,2,...).
    """
    ts = timestamps.reset_index(drop=True)
    order = ts.sort_values().index
    sorted_ts = ts.loc[order]

    gap_seconds = sorted_ts.diff()
    is_new_cu = gap_seconds > (gap_threshold_hours * 3600)
    is_new_cu.iloc[0] = False

    cu_in_sorted_order = is_new_cu.cumsum()

    cu_index = pd.Series(index=order, data=cu_in_sorted_order.values).sort_index()
    return cu_index


cu_index_v2 = assign_cu_index(pd.Series(timestamps), gap_threshold_hours=48.0)
print(cu_index_v2.value_counts().sort_index())

0     11
1     10
2     10
3     15
4     10
5     10
6     10
7     10
8     10
9     10
10    10
11    10
12    10
13    10
14    10
15    10
16    10
17    10
18    10
19    10
20    10
21    10
22    10
23    10
24    10
25    10
26    10
27    10
28     5
Name: count, dtype: int64

In [9]:
import pandas as pd
import glob, os

RAW_DIR = "../data/raw/10.35097-1969/10.35097-1969/data/dataset/cell_eisv2"

def assign_cu_index(timestamps: pd.Series, gap_threshold_hours: float = 48.0) -> pd.Series:
    ts = timestamps.reset_index(drop=True)
    if len(ts) == 0:
        return pd.Series([], dtype=int)
    order = ts.sort_values().index
    sorted_ts = ts.loc[order]
    # first element's diff is NaN -> fillna(False) makes it "not a new CU". Robust, no iloc.
    is_new = (sorted_ts.diff() > gap_threshold_hours * 3600).fillna(False)
    cu = pd.Series(index=order, data=is_new.cumsum().values).sort_index()
    return cu

all_files = sorted(glob.glob(os.path.join(RAW_DIR, "*.csv")))
sample = all_files[:1] + all_files[12:14] + all_files[40:42] + all_files[100:102] + all_files[-2:]

THRESH = 48.0
print(f"{'file':<40}{'rows':>7}{'#spec':>6}{'#CU':>5}{'odd':>5}{'max_within_h':>13}{'min_between_h':>14}")
print("-" * 90)
for f in sample:
    df = pd.read_csv(f, sep=";")
    ts = pd.Series(sorted(df["timestamp_s"].unique()))

    if len(ts) == 0:
        print(f"{os.path.basename(f):<40}{len(df):>7}{'0':>6}{'-':>5}{'-':>5}{'EMPTY / no timestamps':>27}")
        continue

    sorted_ts = ts.sort_values().reset_index(drop=True)
    gaps_h = sorted_ts.diff() / 3600
    cu_sorted = assign_cu_index(sorted_ts, THRESH).reset_index(drop=True)
    is_between = cu_sorted.diff() > 0
    within = gaps_h[~is_between].dropna()
    between = gaps_h[is_between].dropna()

    cu = assign_cu_index(ts, THRESH)
    odd = (cu.value_counts() != 10).sum()

    print(f"{os.path.basename(f):<40}{len(df):>7}{len(ts):>6}{cu.nunique():>5}{odd:>5}"
          f"{within.max():>13.1f}{(between.min() if len(between) else float('nan')):>14.1f}")

file                                       rows #spec  #CU  odd max_within_h min_between_h
------------------------------------------------------------------------------------------
cell_eisv2_P000_0_S20_C00.csv                 0     0    -    -      EMPTY / no timestamps
cell_eisv2_P001_1_S01_C10.csv              8439   291   29    3         31.7         125.3
cell_eisv2_P001_2_S04_C09.csv              8410   290   29    2         31.4         128.4
cell_eisv2_P010_2_S12_C10.csv              8410   290   29    2         32.5         127.7
cell_eisv2_P010_3_S13_C10.csv              8410   290   29    2         32.4         128.1
cell_eisv2_P030_2_S08_C05.csv              2784    96    9    2         14.6         127.0
cell_eisv2_P030_3_S09_C05.csv              2784    96    9    2         12.9         127.9
cell_eisv2_P076_2_S16_C02.csv              8468   292   29    3         29.5         127.5
cell_eisv2_P076_3_S17_C02.csv              8439   291   29    3         29.3         128.9

In [10]:
import glob, os
import pandas as pd

all_files = sorted(glob.glob(os.path.join(RAW_DIR, "*.csv")))
print(f"Total files: {len(all_files)}")

empty, nonempty = [], []
for f in all_files:
    try:
        n = len(pd.read_csv(f, sep=";", usecols=["timestamp_s"]))
    except Exception:
        n = 0
    (empty if n == 0 else nonempty).append(os.path.basename(f))

print(f"Non-empty (real cells): {len(nonempty)}")
print(f"Empty files: {len(empty)}")
print("\nEmpty file names:")
for name in empty:
    print("  ", name)

Total files: 240
Non-empty (real cells): 228
Empty files: 12

Empty file names:
   cell_eisv2_P000_0_S20_C00.csv
   cell_eisv2_P000_0_S20_C01.csv
   cell_eisv2_P000_0_S20_C02.csv
   cell_eisv2_P000_0_S20_C03.csv
   cell_eisv2_P000_0_S20_C04.csv
   cell_eisv2_P000_0_S20_C05.csv
   cell_eisv2_P000_0_S20_C06.csv
   cell_eisv2_P000_0_S20_C07.csv
   cell_eisv2_P000_0_S20_C08.csv
   cell_eisv2_P000_0_S20_C09.csv
   cell_eisv2_P000_0_S20_C10.csv
   cell_eisv2_P000_0_S20_C11.csv

In [1]:
import sys
sys.path.insert(0, "..")
from src.prep.load_eis import process_cell_file

path = "../data/raw/10.35097-1969/10.35097-1969/data/dataset/cell_eisv2/cell_eisv2_P001_1_S01_C10.csv"
out = process_cell_file(path)

print("shape:", out.shape)
print("check-ups:", out["cu_index"].nunique())
spectra = out.groupby(["cu_index", "soc_nom", "is_rt"])
print("number of spectra:", spectra.ngroups)
print("points per spectrum (should all be 28):")
print(spectra.size().value_counts())
out.head()

shape: (7980, 14)
check-ups: 29
number of spectra: 285
points per spectrum (should all be 28):
28    285
Name: count, dtype: int64

,cell_id,pack,replicate,board,channel,cu_index,soc_nom,is_rt,freq_Hz,Z_real_mOhm,Z_imag_mOhm,temp_degC,soh_imp,valid
0,cell_eisv2_P001_1_S01_C10,P001,1,S01,C10,0,10,1,10000.0000,13.758,-11.192,24.95,100.0,1
1,cell_eisv2_P001_1_S01_C10,P001,1,S01,C10,0,10,1,6756.7568,13.839,-7.921,24.95,100.0,1
2,cell_eisv2_P001_1_S01_C10,P001,1,S01,C10,0,10,1,5000.0000,13.997,-5.765,24.95,100.0,1
3,cell_eisv2_P001_1_S01_C10,P001,1,S01,C10,0,10,1,3125.0000,14.177,-3.342,24.95,100.0,1
4,cell_eisv2_P001_1_S01_C10,P001,1,S01,C10,0,10,1,2083.3333,14.380,-1.773,24.95,100.0,1

In [1]:
import sys
sys.path.insert(0, "..")
from src.prep.load_eis import load_all_cells

RAW = "../data/raw/10.35097-1969/10.35097-1969/data/dataset/cell_eisv2"
combined, skipped = load_all_cells(RAW, save_path="../data/interim/eis_spectra.parquet")

print("cells:", combined["cell_id"].nunique())
print("skipped (empty files):", len(skipped))
print("total rows:", len(combined))

spectra = combined.groupby(["cell_id", "cu_index", "soc_nom", "is_rt"])
print("total spectra:", spectra.ngroups)
print("points per spectrum (should be all 28):")
print(spectra.size().value_counts())

cells: 228
skipped (empty files): 12
total rows: 1102304
total spectra: 39368
points per spectrum (should be all 28):
28    39368
Name: count, dtype: int64

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)   # show all 29 columns
pd.set_option("display.width", 250)

labeled = pd.read_parquet("../data/interim/eis_labeled.parquet")
labeled.sample(20)        # 20 random rows as a table

,cell_id,pack,replicate,board,channel,cu_index,timestamp_s,soc_nom,is_rt,freq_Hz,Z_real_mOhm,Z_imag_mOhm,temp_degC,soh_imp,z_ref_init_mOhm,z_ref_now_mOhm,valid,param_id,aging_type,temp_cat,soc_idle_cat,soc_limits_cat,c_rate_cat,profile,temp_setpoint_degC,cell_key,cap_timestamp_s,soh_cap,cap_aged_est_Ah
943669,cell_eisv2_P075_2_S18_C02,P075,2,S18,C02,22,1.704350e+09,50,1,675.6757,16.159,0.393,24.85,87.115401,19.129,24.059,1,75,Profile,D,-,C,A,A,40,P075_2_S18_C02,1.704340e+09,57.600754,2.364011
910081,cell_eisv2_P038_2_S07_C07,P038,2,S07,C07,20,1.700775e+09,10,0,312.5000,29.286,4.342,10.16,70.544875,35.423,56.291,1,38,Cyclic,B,-,C,B,-,10,P038_2_S07_C07,1.700680e+09,29.250893,1.938763
469471,cell_eisv2_P001_1_S01_C10,P001,1,S01,C10,8,1.678969e+09,90,0,675.6757,17.245,1.620,1.46,100.989878,41.067,40.254,1,1,Calendar,A,A,-,-,-,0,P001_1_S01_C10,1.678915e+09,91.844511,2.877668
179222,cell_eisv2_P075_3_S19_C02,P075,3,S19,C02,2,1.668120e+09,30,0,14.7059,15.758,0.252,40.13,99.752402,16.511,16.593,1,75,Profile,D,-,C,A,A,40,P075_3_S19_C02,1.668038e+09,84.648132,2.769722
660905,cell_eisv2_P068_1_S06_C03,P068,1,S06,C03,13,1.687996e+09,50,1,0.5000,27.030,1.759,25.13,81.516171,19.325,26.469,1,68,Profile,B,-,B,A,A,10,P068_1_S06_C03,1.687986e+09,51.284772,2.269272
127577,cell_eisv2_P044_3_S13_C00,P044,3,S13,C00,1,1.666346e+09,10,0,2083.3333,14.032,-1.968,25.63,102.429473,22.766,21.660,1,44,Cyclic,C,-,A,D,-,25,P044_3_S13_C00,1.666230e+09,77.983779,2.669757
791866,cell_eisv2_P050_1_S10_C09,P050,1,S10,C09,17,1.695243e+09,10,1,3.1250,22.418,2.268,24.70,102.018249,24.261,23.281,1,50,Cyclic,C,-,C,B,-,25,P050_1_S10_C09,1.695240e+09,66.483355,2.497250
618506,cell_eisv2_P013_2_S16_C10,P013,2,S16,C10,12,1.686189e+09,10,1,6756.7568,13.866,-8.552,25.05,100.199127,23.399,23.551,1,13,Calendar,D,A,-,-,-,40,P013_2_S16_C10,1.686185e+09,85.683602,2.785254
22150,cell_eisv2_P070_1_S06_C02,P070,1,S06,C02,0,1.665691e+09,70,1,1470.5883,14.602,-1.072,24.91,100.000000,19.496,19.496,1,70,Profile,B,-,C,D,B,10,P070_1_S06_C02,1.665624e+09,96.362847,2.945443
41974,cell_eisv2_P073_1_S11_C02,P073,1,S11,C02,0,1.665743e+09,70,0,3.1250,18.480,0.356,25.46,100.000000,19.223,19.223,1,73,Profile,C,-,C,D,B,25,P073_1_S11_C02,1.665625e+09,97.239971,2.958600
111488,cell_eisv2_P062_1_S16_C07,P062,1,S16,C07,1,1.666318e+09,50,0,147.0588,14.783,0.371,39.69,100.199449,16.495,16.429,1,62,Cyclic,D,-,C,B,-,40,P062_1_S16_C07,1.666231e+09,92.237568,2.883564
741165,cell_eisv2_P015_1_S15_C10,P015,1,S15,C10,15,1.691637e+09,90,1,2.0833,23.575,1.045,25.16,89.085680,19.632,23.917,1,15,Calendar,D,C,-,-,-,40,P015_1_S15_C10,1.691617e+09,71.789807,2.576847
1066055,cell_eisv2_P068_3_S08_C03,P068,3,S08,C03,26,1.711661e+09,10,0,50.0000,37.496,8.225,10.47,47.535444,31.811,65.190,1,68,Profile,B,-,B,A,A,10,P068_3_S08_C03,1.711598e+09,15.121515,1.726823
151634,cell_eisv2_P052_3_S13_C01,P052,3,S13,C01,2,1.668063e+09,70,1,3125.0000,14.221,-3.487,25.24,99.184245,19.640,19.960,1,52,Cyclic,C,-,C,D,-,25,P052_3_S13_C01,1.668030e+09,83.095884,2.746438
1045513,cell_eisv2_P037_3_S10_C04,P037,3,S10,C04,26,1.711606e+09,50,1,675.6757,18.255,0.744,25.01,77.815443,19.371,27.965,1,37,Cyclic,B,-,C,A,-,10,P037_3_S10_C04,1.711596e+09,47.464624,2.211969
799229,cell_eisv2_P003_3_S05_C07,P003,3,S05,C07,17,1.695256e+09,30,1,3125.0000,14.310,-3.894,25.06,100.895643,19.743,19.390,1,3,Calendar,A,C,-,-,-,0,P003_3_S05_C07,1.695250e+09,81.470555,2.722058
812961,cell_eisv2_P075_1_S16_C03,P075,1,S16,C03,17,1.695295e+09,50,0,0.1000,20.628,3.113,39.12,91.201341,16.044,18.868,1,75,Profile,D,-,C,A,A,40,P075_1_S16_C03,1.695247e+09,60.876703,2.413151
415005,cell_eisv2_P005_1_S07_C09,P005,1,S07,C09,7,1.677119e+09,70,1,1470.5883,14.756,-1.029,24.98,100.350249,19.467,19.330,1,5,Calendar,B,A,-,-,-,10,P005_1_S07_C09,1.677101e+09,90.997267,2.864959
394711,cell_eisv2_P022_2_S04_C06,P022,2,S04,C06,6,1.675368e+09,30,0,50.0000,30.063,8.194,1.50,81.226462,38.731,53.274,1,22,Cyclic,A,-,B,B,-,0,P022_2_S04_C06,1.675283e+09,53.964776,2.309472
616781,cell_eisv2_P076_3_S17_C02,P076,3,S17,C02,12,1.686186e+09,10,1,2083.3333,15.050,-2.024,25.02,100.948691,24.191,23.732,1,76,Profile,D,-,C,D,B,40,P076_3_S17_C02,1.686184e+09,61.773604,2.426604